/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is true */

#line 5 "sort-5.c"
void __globinit_sort_5(void) ;
extern void __CrownInit(int id )  __attribute__((__crown_skip__)) ;
extern void __CrownHandleReturn(int id , int type , long long val , double fp_val )  __attribute__((__crown_skip__)) ;
extern void __CrownReturn(int id )  __attribute__((__crown_skip__)) ;
extern void __CrownCall(int id , unsigned int fid )  __attribute__((__crown_skip__)) ;
extern void __CrownBranch(int id , int bid , unsigned char b , int line , char *fname )  __attribute__((__crown_skip__)) ;
extern void __CrownApply2(int id , int op , int type , long long val , double fp_val )  __attribute__((__crown_skip__)) ;
extern void __CrownApply1(int id , int op , int type , long long val , double fp_val )  __attribute__((__crown_skip__)) ;
extern void __CrownClearStack(int id )  __attribute__((__crown_skip__)) ;
extern void __CrownStore(int id , unsigned long addr )  __attribute__((__crown_skip__)) ;
extern void __CrownLoad(int id , unsigned long addr , int type , long long val , double fp_val )  __attribute__((__crown_skip__)) ;
#line 307 "/home/moonzoo/CROWN/bin/../include/crown.h"
extern void __CrownUInt(unsigned int *x , int cnt_sym_var , int ln , char *fname 
                        , ...)  __attribute__((__crown_skip__)) ;
#line 362 "/usr/include/stdio.h"
extern int printf(char const   * __restrict  __format  , ...) ;
#line 695
extern int puts(char const   *__s ) ;
#line 69 "/usr/include/assert.h"
extern  __attribute__((__nothrow__, __noreturn__)) void ( __attribute__((__leaf__)) __assert_fail)(char const   *__assertion ,
                                                                                                   char const   *__file ,
                                                                                                   unsigned int __line ,
                                                                                                   char const   *__function ) ;
#line 8 "sort-5.c"
int main(void) ;
#line 8 "sort-5.c"
static int cnt_symbolic_var  =    1;
#line 5 "sort-5.c"
int main(void) 
{ 
  unsigned int a[5] ;
  unsigned int i ;
  unsigned int j ;
  unsigned int tmp ;
  int __retres5 ;

  {
  __globinit_sort_5();
  __CrownCall(2, 1);
  __CrownClearStack(1);
  __CrownLoad(3, (unsigned long )0, 4, (long long )0U, (double )0U);
  __CrownStore(4, (unsigned long )(& i));
#line 8
  i = 0U;
#line 8
  while (1) {
    while_continue: /* CIL Label */ ;
    {
    __CrownLoad(7, (unsigned long )(& i), 4, (long long )i, (double )i);
    __CrownLoad(6, (unsigned long )0, 4, (long long )5U, (double )5U);
    __CrownApply2(5, 19, 5, (long long )(i < 5U), (double )(i < 5U));
#line 8
    if (i < 5U) {
      __CrownBranch(8, 6, 1, __LINE__, __FILE__);

    } 
      #line 8
      else {
      __CrownBranch(9, 7, 0, __LINE__, __FILE__);
#line 8
      goto while_break;
    }
    }
#line 8
    __CrownUInt(& a[i], cnt_symbolic_var, 8, (char *)"sort-5.c", "a[i]");
    __CrownLoad(12, (unsigned long )(& cnt_symbolic_var), 5, (long long )cnt_symbolic_var,
                (double )cnt_symbolic_var);
    __CrownLoad(11, (unsigned long )0, 5, (long long )1, (double )1);
    __CrownApply2(10, 0, 5, (long long )(cnt_symbolic_var + 1), (double )(cnt_symbolic_var + 1));
    __CrownStore(13, (unsigned long )(& cnt_symbolic_var));
#line 8
    cnt_symbolic_var ++;
    __CrownLoad(14, (unsigned long )0, 6, (long long )((char const   * __restrict  )"%u,"),
                8);
    __CrownLoad(15, (unsigned long )(& a[i]), 4, (long long )a[i], (double )a[i]);
#line 8
    printf((char const   * __restrict  )"%u,", a[i]);
    __CrownClearStack(16);
    __CrownLoad(19, (unsigned long )(& i), 4, (long long )i, (double )i);
    __CrownLoad(18, (unsigned long )0, 4, (long long )1U, (double )1U);
    __CrownApply2(17, 0, 4, (long long )(i + 1U), (double )(i + 1U));
    __CrownStore(20, (unsigned long )(& i));
#line 8
    i ++;
  }
  while_break: /* CIL Label */ 
  __CrownLoad(21, (unsigned long )0, 6, (long long )"", 8);
#line 9
  puts("");
  __CrownClearStack(22);
  __CrownLoad(23, (unsigned long )0, 4, (long long )0U, (double )0U);
  __CrownStore(24, (unsigned long )(& i));
#line 11
  i = 0U;
#line 11
  while (1) {
    while_continue___0: /* CIL Label */ ;
    {
    __CrownLoad(27, (unsigned long )(& i), 4, (long long )i, (double )i);
    __CrownLoad(26, (unsigned long )0, 4, (long long )4U, (double )4U);
    __CrownApply2(25, 19, 5, (long long )(i < 4U), (double )(i < 4U));
#line 11
    if (i < 4U) {
      __CrownBranch(28, 15, 1, __LINE__, __FILE__);

    } 
      #line 11
      else {
      __CrownBranch(29, 16, 0, __LINE__, __FILE__);
#line 11
      goto while_break___0;
    }
    }
    __CrownLoad(32, (unsigned long )(& i), 4, (long long )i, (double )i);
    __CrownLoad(31, (unsigned long )0, 4, (long long )1U, (double )1U);
    __CrownApply2(30, 0, 4, (long long )(i + 1U), (double )(i + 1U));
    __CrownStore(33, (unsigned long )(& j));
#line 12
    j = i + 1U;
    {
#line 12
    while (1) {
      while_continue___1: /* CIL Label */ ;
      {
      __CrownLoad(36, (unsigned long )(& j), 4, (long long )j, (double )j);
      __CrownLoad(35, (unsigned long )0, 4, (long long )5U, (double )5U);
      __CrownApply2(34, 19, 5, (long long )(j < 5U), (double )(j < 5U));
#line 12
      if (j < 5U) {
        __CrownBranch(37, 22, 1, __LINE__, __FILE__);

      } 
        #line 12
        else {
        __CrownBranch(38, 23, 0, __LINE__, __FILE__);
#line 12
        goto while_break___1;
      }
      }
      {
      __CrownLoad(41, (unsigned long )(& a[i]), 4, (long long )a[i], (double )a[i]);
      __CrownLoad(40, (unsigned long )(& a[j]), 4, (long long )a[j], (double )a[j]);
      __CrownApply2(39, 15, 5, (long long )(a[i] > a[j]), (double )(a[i] > a[j]));
#line 13
      if (a[i] > a[j]) {
        __CrownBranch(42, 25, 1, __LINE__, __FILE__);
        __CrownLoad(44, (unsigned long )(& a[i]), 4, (long long )a[i], (double )a[i]);
        __CrownStore(45, (unsigned long )(& tmp));
#line 14
        tmp = a[i];
        __CrownLoad(46, (unsigned long )(& a[j]), 4, (long long )a[j], (double )a[j]);
        __CrownStore(47, (unsigned long )(& a[i]));
#line 15
        a[i] = a[j];
        __CrownLoad(48, (unsigned long )(& tmp), 4, (long long )tmp, (double )tmp);
        __CrownStore(49, (unsigned long )(& a[j]));
#line 16
        a[j] = tmp;
      } 
        #line 13
        else {
        __CrownBranch(43, 26, 0, __LINE__, __FILE__);

      }
      }
      __CrownLoad(52, (unsigned long )(& j), 4, (long long )j, (double )j);
      __CrownLoad(51, (unsigned long )0, 4, (long long )1U, (double )1U);
      __CrownApply2(50, 0, 4, (long long )(j + 1U), (double )(j + 1U));
      __CrownStore(53, (unsigned long )(& j));
#line 12
      j ++;
    }
    while_break___1: /* CIL Label */ ;
    }
    __CrownLoad(56, (unsigned long )(& i), 4, (long long )i, (double )i);
    __CrownLoad(55, (unsigned long )0, 4, (long long )1U, (double )1U);
    __CrownApply2(54, 0, 4, (long long )(i + 1U), (double )(i + 1U));
    __CrownStore(57, (unsigned long )(& i));
#line 11
    i ++;
  }
  while_break___0: /* CIL Label */ 
  __CrownLoad(58, (unsigned long )0, 4, (long long )0U, (double )0U);
  __CrownStore(59, (unsigned long )(& i));
#line 19
  i = 0U;
#line 19
  while (1) {
    while_continue___2: /* CIL Label */ ;
    {
    __CrownLoad(62, (unsigned long )(& i), 4, (long long )i, (double )i);
    __CrownLoad(61, (unsigned long )0, 4, (long long )4U, (double )4U);
    __CrownApply2(60, 19, 5, (long long )(i < 4U), (double )(i < 4U));
#line 19
    if (i < 4U) {
      __CrownBranch(63, 36, 1, __LINE__, __FILE__);

    } 
      #line 19
      else {
      __CrownBranch(64, 37, 0, __LINE__, __FILE__);
#line 19
      goto while_break___2;
    }
    }
    {
    __CrownLoad(67, (unsigned long )(& a[i]), 4, (long long )a[i], (double )a[i]);
    __CrownLoad(66, (unsigned long )(& a[i + 1U]), 4, (long long )a[i + 1U], (double )a[i + 1U]);
    __CrownApply2(65, 17, 5, (long long )(a[i] <= a[i + 1U]), (double )(a[i] <= a[i + 1U]));
#line 20
    if (a[i] <= a[i + 1U]) {
      __CrownBranch(68, 39, 1, __LINE__, __FILE__);

    } 
      #line 20
      else {
      __CrownBranch(69, 40, 0, __LINE__, __FILE__);
      __CrownLoad(70, (unsigned long )0, 6, (long long )"a[i] <= a[i+1]", 8);
      __CrownLoad(71, (unsigned long )0, 6, (long long )"sort-5.c", 8);
      __CrownLoad(72, (unsigned long )0, 4, (long long )20U, (double )20U);
      __CrownLoad(73, (unsigned long )0, 6, (long long )"main", 8);
#line 20
      __assert_fail("a[i] <= a[i+1]", "sort-5.c", 20U, "main");
      __CrownClearStack(74);
    }
    }
    __CrownLoad(77, (unsigned long )(& i), 4, (long long )i, (double )i);
    __CrownLoad(76, (unsigned long )0, 4, (long long )1U, (double )1U);
    __CrownApply2(75, 0, 4, (long long )(i + 1U), (double )(i + 1U));
    __CrownStore(78, (unsigned long )(& i));
#line 19
    i ++;
  }
  while_break___2: /* CIL Label */ 
  __CrownLoad(79, (unsigned long )0, 5, (long long )0, (double )0);
  __CrownStore(80, (unsigned long )(& __retres5));
#line 21
  __retres5 = 0;
  __CrownLoad(81, (unsigned long )(& __retres5), 5, (long long )__retres5, (double )__retres5);
  __CrownReturn(82);
#line 5
  return (__retres5);
}
}
void __globinit_sort_5(void) 
{ 


  {
  __CrownInit(83);
}
}
