/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is true */

#line 5 "sort-6.c"
void __globinit_sort_6(void) ;
extern void __CrownInit(int id )  __attribute__((__crown_skip__)) ;
extern void __CrownCheckSymbolic(int id , char *fname )  __attribute__((__crown_skip__)) ;
extern void __CrownEnableSymbolic(int id , char *fname )  __attribute__((__crown_skip__)) ;
extern void __CrownSetCallerCalleeName(int id , char *fname , char *fname2 )  __attribute__((__crown_skip__)) ;
extern void __CrownHandleReturn(int id , int type , long long val , double fp_val )  __attribute__((__crown_skip__)) ;
extern void __CrownReturn(int id )  __attribute__((__crown_skip__)) ;
extern void __CrownCall(int id , unsigned int fid )  __attribute__((__crown_skip__)) ;
extern void __CrownBranch(int id , int bid , unsigned char b , int line , char *fname )  __attribute__((__crown_skip__)) ;
extern void __CrownApply2(int id , int op , int type , long long val , double fp_val )  __attribute__((__crown_skip__)) ;
extern void __CrownApply1(int id , int op , int type , long long val , double fp_val )  __attribute__((__crown_skip__)) ;
extern void __CrownClearStack(int id )  __attribute__((__crown_skip__)) ;
extern void __CrownStore(int id , unsigned long addr )  __attribute__((__crown_skip__)) ;
extern void __CrownLoad(int id , unsigned long addr , int type , long long val , double fp_val )  __attribute__((__crown_skip__)) ;
#line 371 "/mnt/c/ubuntu/CROWN/bin/../include/crown.h"
extern void __CrownUInt(unsigned int *x , int cnt_sym_var , int ln , char *fname 
                        , ...)  __attribute__((__crown_skip__)) ;
#line 69 "/usr/include/assert.h"
extern  __attribute__((__nothrow__, __noreturn__)) void ( __attribute__((__leaf__)) __assert_fail)(char const   *__assertion ,
                                                                                                   char const   *__file ,
                                                                                                   unsigned int __line ,
                                                                                                   char const   *__function ) ;
#line 8 "sort-6.c"
int main(void) ;
#line 8 "sort-6.c"
static int cnt_symbolic_var  =    1;
#line 5 "sort-6.c"
int main(void) 
{ 
  unsigned int a[6] ;
  unsigned int i ;
  unsigned int j ;
  unsigned int tmp ;
  int __retres5 ;

  {
  __globinit_sort_6();
  __CrownCheckSymbolic(3, "main");
  __CrownCall(2, 1);
  __CrownClearStack(1);
  __CrownLoad(4, (unsigned long )0, 4, (long long )0U, (double )0U);
  __CrownStore(5, (unsigned long )(& i));
#line 8
  i = 0U;
#line 8
  while (1) {
    while_continue: /* CIL Label */ ;
    {
    __CrownLoad(8, (unsigned long )(& i), 4, (long long )i, (double )i);
    __CrownLoad(7, (unsigned long )0, 4, (long long )6U, (double )6U);
    __CrownApply2(6, 19, 5, (long long )(i < 6U), (double )(i < 6U));
#line 8
    if (i < 6U) {
      __CrownBranch(9, 6, 1, __LINE__, __FILE__);

    } 
      #line 8
      else {
      __CrownBranch(10, 7, 0, __LINE__, __FILE__);
#line 8
      goto while_break;
    }
    }
#line 8
    __CrownUInt(& a[i], cnt_symbolic_var, 8, (char *)"sort-6.c", "a[i]");
    __CrownLoad(13, (unsigned long )(& cnt_symbolic_var), 5, (long long )cnt_symbolic_var,
                (double )cnt_symbolic_var);
    __CrownLoad(12, (unsigned long )0, 5, (long long )1, (double )1);
    __CrownApply2(11, 0, 5, (long long )(cnt_symbolic_var + 1), (double )(cnt_symbolic_var + 1));
    __CrownStore(14, (unsigned long )(& cnt_symbolic_var));
#line 8
    cnt_symbolic_var ++;
    __CrownLoad(17, (unsigned long )(& i), 4, (long long )i, (double )i);
    __CrownLoad(16, (unsigned long )0, 4, (long long )1U, (double )1U);
    __CrownApply2(15, 0, 4, (long long )(i + 1U), (double )(i + 1U));
    __CrownStore(18, (unsigned long )(& i));
#line 8
    i ++;
  }
  while_break: /* CIL Label */ 
  __CrownLoad(19, (unsigned long )0, 4, (long long )0U, (double )0U);
  __CrownStore(20, (unsigned long )(& i));
#line 11
  i = 0U;
#line 11
  while (1) {
    while_continue___0: /* CIL Label */ ;
    {
    __CrownLoad(23, (unsigned long )(& i), 4, (long long )i, (double )i);
    __CrownLoad(22, (unsigned long )0, 4, (long long )5U, (double )5U);
    __CrownApply2(21, 19, 5, (long long )(i < 5U), (double )(i < 5U));
#line 11
    if (i < 5U) {
      __CrownBranch(24, 15, 1, __LINE__, __FILE__);

    } 
      #line 11
      else {
      __CrownBranch(25, 16, 0, __LINE__, __FILE__);
#line 11
      goto while_break___0;
    }
    }
    __CrownLoad(28, (unsigned long )(& i), 4, (long long )i, (double )i);
    __CrownLoad(27, (unsigned long )0, 4, (long long )1U, (double )1U);
    __CrownApply2(26, 0, 4, (long long )(i + 1U), (double )(i + 1U));
    __CrownStore(29, (unsigned long )(& j));
#line 12
    j = i + 1U;
    {
#line 12
    while (1) {
      while_continue___1: /* CIL Label */ ;
      {
      __CrownLoad(32, (unsigned long )(& j), 4, (long long )j, (double )j);
      __CrownLoad(31, (unsigned long )0, 4, (long long )6U, (double )6U);
      __CrownApply2(30, 19, 5, (long long )(j < 6U), (double )(j < 6U));
#line 12
      if (j < 6U) {
        __CrownBranch(33, 22, 1, __LINE__, __FILE__);

      } 
        #line 12
        else {
        __CrownBranch(34, 23, 0, __LINE__, __FILE__);
#line 12
        goto while_break___1;
      }
      }
      {
      __CrownLoad(37, (unsigned long )(& a[i]), 4, (long long )a[i], (double )a[i]);
      __CrownLoad(36, (unsigned long )(& a[j]), 4, (long long )a[j], (double )a[j]);
      __CrownApply2(35, 15, 5, (long long )(a[i] > a[j]), (double )(a[i] > a[j]));
#line 13
      if (a[i] > a[j]) {
        __CrownBranch(38, 25, 1, __LINE__, __FILE__);
        __CrownLoad(40, (unsigned long )(& a[i]), 4, (long long )a[i], (double )a[i]);
        __CrownStore(41, (unsigned long )(& tmp));
#line 14
        tmp = a[i];
        __CrownLoad(42, (unsigned long )(& a[j]), 4, (long long )a[j], (double )a[j]);
        __CrownStore(43, (unsigned long )(& a[i]));
#line 15
        a[i] = a[j];
        __CrownLoad(44, (unsigned long )(& tmp), 4, (long long )tmp, (double )tmp);
        __CrownStore(45, (unsigned long )(& a[j]));
#line 16
        a[j] = tmp;
      } 
        #line 13
        else {
        __CrownBranch(39, 26, 0, __LINE__, __FILE__);

      }
      }
      __CrownLoad(48, (unsigned long )(& j), 4, (long long )j, (double )j);
      __CrownLoad(47, (unsigned long )0, 4, (long long )1U, (double )1U);
      __CrownApply2(46, 0, 4, (long long )(j + 1U), (double )(j + 1U));
      __CrownStore(49, (unsigned long )(& j));
#line 12
      j ++;
    }
    while_break___1: /* CIL Label */ ;
    }
    __CrownLoad(52, (unsigned long )(& i), 4, (long long )i, (double )i);
    __CrownLoad(51, (unsigned long )0, 4, (long long )1U, (double )1U);
    __CrownApply2(50, 0, 4, (long long )(i + 1U), (double )(i + 1U));
    __CrownStore(53, (unsigned long )(& i));
#line 11
    i ++;
  }
  while_break___0: /* CIL Label */ 
  __CrownLoad(54, (unsigned long )0, 4, (long long )0U, (double )0U);
  __CrownStore(55, (unsigned long )(& i));
#line 19
  i = 0U;
#line 19
  while (1) {
    while_continue___2: /* CIL Label */ ;
    {
    __CrownLoad(58, (unsigned long )(& i), 4, (long long )i, (double )i);
    __CrownLoad(57, (unsigned long )0, 4, (long long )5U, (double )5U);
    __CrownApply2(56, 19, 5, (long long )(i < 5U), (double )(i < 5U));
#line 19
    if (i < 5U) {
      __CrownBranch(59, 36, 1, __LINE__, __FILE__);

    } 
      #line 19
      else {
      __CrownBranch(60, 37, 0, __LINE__, __FILE__);
#line 19
      goto while_break___2;
    }
    }
    {
    __CrownLoad(63, (unsigned long )(& a[i]), 4, (long long )a[i], (double )a[i]);
    __CrownLoad(62, (unsigned long )(& a[i + 1U]), 4, (long long )a[i + 1U], (double )a[i + 1U]);
    __CrownApply2(61, 17, 5, (long long )(a[i] <= a[i + 1U]), (double )(a[i] <= a[i + 1U]));
#line 20
    if (a[i] <= a[i + 1U]) {
      __CrownBranch(64, 39, 1, __LINE__, __FILE__);

    } 
      #line 20
      else {
      __CrownBranch(65, 40, 0, __LINE__, __FILE__);
      __CrownSetCallerCalleeName(67, "main", "__assert_fail");
#line 20
      __assert_fail("a[i] <= a[i+1]", "sort-6.c", 20U, "main");
      __CrownEnableSymbolic(66, "main");
    }
    }
    __CrownLoad(70, (unsigned long )(& i), 4, (long long )i, (double )i);
    __CrownLoad(69, (unsigned long )0, 4, (long long )1U, (double )1U);
    __CrownApply2(68, 0, 4, (long long )(i + 1U), (double )(i + 1U));
    __CrownStore(71, (unsigned long )(& i));
#line 19
    i ++;
  }
  while_break___2: /* CIL Label */ 
  __CrownLoad(72, (unsigned long )0, 5, (long long )0, (double )0);
  __CrownStore(73, (unsigned long )(& __retres5));
#line 21
  __retres5 = 0;
  __CrownLoad(74, (unsigned long )(& __retres5), 5, (long long )__retres5, (double )__retres5);
  __CrownReturn(75);
#line 5
  return (__retres5);
}
}
void __globinit_sort_6(void) 
{ 


  {
  __CrownInit(76);
}
}
