/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is true */

#line 6 "triangle.c"
void __globinit_triangle(void) ;
extern void __CrownInit(int id )  __attribute__((__crown_skip__)) ;
extern void __CrownCheckSymbolic(int id , char *fname )  __attribute__((__crown_skip__)) ;
extern void __CrownEnableSymbolic(int id , char *fname )  __attribute__((__crown_skip__)) ;
extern void __CrownSetCallerCalleeName(int id , char *fname , char *fname2 )  __attribute__((__crown_skip__)) ;
extern void __CrownHandleReturn(int id , int type , long long val , double fp_val )  __attribute__((__crown_skip__)) ;
extern void __CrownReturn(int id )  __attribute__((__crown_skip__)) ;
extern void __CrownCall(int id , unsigned int fid )  __attribute__((__crown_skip__)) ;
extern void __CrownBranch(int id , int bid , unsigned char b , int line , char *fname )  __attribute__((__crown_skip__)) ;
extern void __CrownApply2(int id , int op , int type , long long val , double fp_val )  __attribute__((__crown_skip__)) ;
extern void __CrownApply1(int id , int op , int type , long long val , double fp_val )  __attribute__((__crown_skip__)) ;
extern void __CrownClearStack(int id )  __attribute__((__crown_skip__)) ;
extern void __CrownStore(int id , unsigned long addr )  __attribute__((__crown_skip__)) ;
extern void __CrownLoad(int id , unsigned long addr , int type , long long val , double fp_val )  __attribute__((__crown_skip__)) ;
#line 216 "/usr/lib/gcc/x86_64-linux-gnu/5/include/stddef.h"
typedef unsigned long size_t;
#line 131 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef long __off_t;
#line 132 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef long __off64_t;
#line 44 "/usr/include/stdio.h"
struct _IO_FILE;
#line 44
struct _IO_FILE;
#line 48 "/usr/include/stdio.h"
typedef struct _IO_FILE FILE;
#line 144 "/usr/include/libio.h"
struct _IO_FILE;
#line 150 "/usr/include/libio.h"
typedef void _IO_lock_t;
#line 156 "/usr/include/libio.h"
struct _IO_marker {
   struct _IO_marker *_next ;
   struct _IO_FILE *_sbuf ;
   int _pos ;
};
#line 241 "/usr/include/libio.h"
struct _IO_FILE {
   int _flags ;
   char *_IO_read_ptr ;
   char *_IO_read_end ;
   char *_IO_read_base ;
   char *_IO_write_base ;
   char *_IO_write_ptr ;
   char *_IO_write_end ;
   char *_IO_buf_base ;
   char *_IO_buf_end ;
   char *_IO_save_base ;
   char *_IO_backup_base ;
   char *_IO_save_end ;
   struct _IO_marker *_markers ;
   struct _IO_FILE *_chain ;
   int _fileno ;
   int _flags2 ;
   __off_t _old_offset ;
   unsigned short _cur_column ;
   signed char _vtable_offset ;
   char _shortbuf[1] ;
   _IO_lock_t *_lock ;
   __off64_t _offset ;
   void *__pad1 ;
   void *__pad2 ;
   void *__pad3 ;
   void *__pad4 ;
   size_t __pad5 ;
   int _mode ;
   char _unused2[(15UL * sizeof(int ) - 4UL * sizeof(void *)) - sizeof(size_t )] ;
};
#line 543 "/usr/include/stdlib.h"
extern  __attribute__((__nothrow__, __noreturn__)) void ( __attribute__((__leaf__)) exit)(int __status ) ;
#line 170 "/usr/include/stdio.h"
extern struct _IO_FILE *stderr ;
#line 237
extern int fclose(FILE *__stream ) ;
#line 272
extern FILE *fopen(char const   * __restrict  __filename , char const   * __restrict  __modes ) ;
#line 356
extern int fprintf(FILE * __restrict  __stream , char const   * __restrict  __format 
                   , ...) ;
#line 362
extern int printf(char const   * __restrict  __format  , ...) ;
#line 125 "/usr/include/string.h"
extern  __attribute__((__nothrow__)) char *( __attribute__((__nonnull__(1,2), __leaf__)) strcpy)(char * __restrict  __dest ,
                                                                                                 char const   * __restrict  __src ) ;
#line 376 "/home/moonzoo/CROWN-SYM_assume/bin/../include/crown.h"
extern void __CrownInt(int *x , int cnt_sym_var , int ln , char *fname  , ...)  __attribute__((__crown_skip__)) ;
#line 8 "triangle.c"
int main(void) ;
#line 8 "triangle.c"
static int cnt_symbolic_var  =    1;
#line 8
int main(void) ;
#line 8 "triangle.c"
static int cnt_symbolic_var___0  =    1;
#line 8
int main(void) ;
#line 8 "triangle.c"
static int cnt_symbolic_var___1  =    1;
#line 6 "triangle.c"
int main(void) 
{ 
  int a ;
  int b ;
  int c ;
  int match ;
  FILE *f ;
  FILE *tmp ;
  FILE *f___0 ;
  FILE *tmp___0 ;
  FILE *f___1 ;
  FILE *tmp___1 ;
  int result ;
  char triangle_type[20] ;
  int __retres13 ;

  {
  __globinit_triangle();
  __CrownCheckSymbolic(3, "main");
  __CrownCall(2, 1);
  __CrownClearStack(1);
  __CrownLoad(4, (unsigned long )0, 5, (long long )0, (double )0);
  __CrownStore(5, (unsigned long )(& match));
#line 7
  match = 0;
#line 8
  __CrownInt(& a, cnt_symbolic_var, 8, (char *)"triangle.c", "a");
  __CrownLoad(8, (unsigned long )(& cnt_symbolic_var), 5, (long long )cnt_symbolic_var,
              (double )cnt_symbolic_var);
  __CrownLoad(7, (unsigned long )0, 5, (long long )1, (double )1);
  __CrownApply2(6, 0, 5, (long long )(cnt_symbolic_var + 1), (double )(cnt_symbolic_var + 1));
  __CrownStore(9, (unsigned long )(& cnt_symbolic_var));
#line 8
  cnt_symbolic_var ++;
#line 8
  __CrownInt(& b, cnt_symbolic_var___0, 8, (char *)"triangle.c", "b");
  __CrownLoad(12, (unsigned long )(& cnt_symbolic_var___0), 5, (long long )cnt_symbolic_var___0,
              (double )cnt_symbolic_var___0);
  __CrownLoad(11, (unsigned long )0, 5, (long long )1, (double )1);
  __CrownApply2(10, 0, 5, (long long )(cnt_symbolic_var___0 + 1), (double )(cnt_symbolic_var___0 + 1));
  __CrownStore(13, (unsigned long )(& cnt_symbolic_var___0));
#line 8
  cnt_symbolic_var___0 ++;
#line 8
  __CrownInt(& c, cnt_symbolic_var___1, 8, (char *)"triangle.c", "c");
  __CrownLoad(16, (unsigned long )(& cnt_symbolic_var___1), 5, (long long )cnt_symbolic_var___1,
              (double )cnt_symbolic_var___1);
  __CrownLoad(15, (unsigned long )0, 5, (long long )1, (double )1);
  __CrownApply2(14, 0, 5, (long long )(cnt_symbolic_var___1 + 1), (double )(cnt_symbolic_var___1 + 1));
  __CrownStore(17, (unsigned long )(& cnt_symbolic_var___1));
#line 8
  cnt_symbolic_var___1 ++;
#line 9
  while (1) {
    while_continue: /* CIL Label */ ;
    {
    __CrownLoad(20, (unsigned long )0, 5, (long long )-10, (double )-10);
    __CrownLoad(19, (unsigned long )(& a), 5, (long long )a, (double )a);
    __CrownApply2(18, 20, 5, (long long )(-10 < a), (double )(-10 < a));
#line 9
    if (-10 < a) {
      __CrownBranch(21, 6, 1, __LINE__, __FILE__);
      {
      __CrownLoad(25, (unsigned long )(& a), 5, (long long )a, (double )a);
      __CrownLoad(24, (unsigned long )0, 5, (long long )10, (double )10);
      __CrownApply2(23, 20, 5, (long long )(a < 10), (double )(a < 10));
#line 9
      if (a < 10) {
        __CrownBranch(26, 7, 1, __LINE__, __FILE__);

      } 
        #line 9
        else {
        __CrownBranch(27, 8, 0, __LINE__, __FILE__);
#line 9
        goto _L;
      }
      }
    } 
      #line 9
      else {
      __CrownBranch(22, 9, 0, __LINE__, __FILE__);
      _L: /* CIL Label */ 
      __CrownLoad(29, (unsigned long )(& stderr), 6, (long long )stderr, 8);
      __CrownApply1(28, 27, 6, (long long )((FILE * __restrict  )stderr), 8);
      __CrownLoad(30, (unsigned long )0, 6, (long long )((char const   * __restrict  )"### SYM_assume(%s) is violated at Line %d (%s in %s) ###\n"),
                  8);
      __CrownLoad(31, (unsigned long )0, 6, (long long )"-10 <a && a < 10", 8);
      __CrownLoad(32, (unsigned long )0, 5, (long long )9, (double )9);
      __CrownLoad(33, (unsigned long )0, 6, (long long )"main", 8);
      __CrownLoad(34, (unsigned long )0, 6, (long long )"triangle.c", 8);
      __CrownSetCallerCalleeName(35, "main", "fprintf");
#line 9
      fprintf((FILE * __restrict  )stderr, (char const   * __restrict  )"### SYM_assume(%s) is violated at Line %d (%s in %s) ###\n",
              "-10 <a && a < 10", 9, "main", "triangle.c");
      __CrownEnableSymbolic(37, "main");
      __CrownClearStack(36);
      __CrownLoad(38, (unsigned long )0, 6, (long long )((char const   * __restrict  )"__SYM_assume_violated"),
                  8);
      __CrownLoad(39, (unsigned long )0, 6, (long long )((char const   * __restrict  )"w"),
                  8);
      __CrownSetCallerCalleeName(40, "main", "fopen");
#line 9
      tmp = fopen((char const   * __restrict  )"__SYM_assume_violated", (char const   * __restrict  )"w");
      __CrownEnableSymbolic(43, "main");
      __CrownHandleReturn(42, 6, (long long )tmp, 8);
      __CrownStore(41, (unsigned long )(& tmp));
      __CrownLoad(44, (unsigned long )(& tmp), 6, (long long )tmp, 8);
      __CrownStore(45, (unsigned long )(& f));
#line 9
      f = tmp;
      {
      __CrownLoad(47, (unsigned long )(& f), 6, (long long )f, 8);
      __CrownApply1(46, 26, 5, (long long )(! f), (double )(! f));
#line 9
      if (! f) {
        __CrownBranch(48, 11, 1, __LINE__, __FILE__);
        __CrownLoad(51, (unsigned long )(& stderr), 6, (long long )stderr, 8);
        __CrownApply1(50, 27, 6, (long long )((FILE * __restrict  )stderr), 8);
        __CrownLoad(52, (unsigned long )0, 6, (long long )((char const   * __restrict  )"### %s file cannot be created ###\n"),
                    8);
        __CrownLoad(53, (unsigned long )0, 6, (long long )"__SYM_assume_violated",
                    8);
        __CrownSetCallerCalleeName(54, "main", "fprintf");
#line 9
        fprintf((FILE * __restrict  )stderr, (char const   * __restrict  )"### %s file cannot be created ###\n",
                "__SYM_assume_violated");
        __CrownEnableSymbolic(56, "main");
        __CrownClearStack(55);
      } 
        #line 9
        else {
        __CrownBranch(49, 12, 0, __LINE__, __FILE__);
        __CrownLoad(57, (unsigned long )(& f), 6, (long long )f, 8);
        __CrownSetCallerCalleeName(58, "main", "fclose");
#line 9
        fclose(f);
        __CrownEnableSymbolic(60, "main");
        __CrownClearStack(59);
      }
      }
      __CrownLoad(61, (unsigned long )0, 5, (long long )1, (double )1);
      __CrownSetCallerCalleeName(62, "main", "exit");
#line 9
      exit(1);
      __CrownEnableSymbolic(64, "main");
      __CrownClearStack(63);
    }
    }
#line 9
    goto while_break;
  }
  while_break: /* CIL Label */ ;
#line 10
  while (1) {
    while_continue___0: /* CIL Label */ ;
    {
    __CrownLoad(67, (unsigned long )0, 5, (long long )-10, (double )-10);
    __CrownLoad(66, (unsigned long )(& b), 5, (long long )b, (double )b);
    __CrownApply2(65, 20, 5, (long long )(-10 < b), (double )(-10 < b));
#line 10
    if (-10 < b) {
      __CrownBranch(68, 20, 1, __LINE__, __FILE__);
      {
      __CrownLoad(72, (unsigned long )(& b), 5, (long long )b, (double )b);
      __CrownLoad(71, (unsigned long )0, 5, (long long )10, (double )10);
      __CrownApply2(70, 20, 5, (long long )(b < 10), (double )(b < 10));
#line 10
      if (b < 10) {
        __CrownBranch(73, 21, 1, __LINE__, __FILE__);

      } 
        #line 10
        else {
        __CrownBranch(74, 22, 0, __LINE__, __FILE__);
#line 10
        goto _L___0;
      }
      }
    } 
      #line 10
      else {
      __CrownBranch(69, 23, 0, __LINE__, __FILE__);
      _L___0: /* CIL Label */ 
      __CrownLoad(76, (unsigned long )(& stderr), 6, (long long )stderr, 8);
      __CrownApply1(75, 27, 6, (long long )((FILE * __restrict  )stderr), 8);
      __CrownLoad(77, (unsigned long )0, 6, (long long )((char const   * __restrict  )"### SYM_assume(%s) is violated at Line %d (%s in %s) ###\n"),
                  8);
      __CrownLoad(78, (unsigned long )0, 6, (long long )"-10 < b && b < 10", 8);
      __CrownLoad(79, (unsigned long )0, 5, (long long )10, (double )10);
      __CrownLoad(80, (unsigned long )0, 6, (long long )"main", 8);
      __CrownLoad(81, (unsigned long )0, 6, (long long )"triangle.c", 8);
      __CrownSetCallerCalleeName(82, "main", "fprintf");
#line 10
      fprintf((FILE * __restrict  )stderr, (char const   * __restrict  )"### SYM_assume(%s) is violated at Line %d (%s in %s) ###\n",
              "-10 < b && b < 10", 10, "main", "triangle.c");
      __CrownEnableSymbolic(84, "main");
      __CrownClearStack(83);
      __CrownLoad(85, (unsigned long )0, 6, (long long )((char const   * __restrict  )"__SYM_assume_violated"),
                  8);
      __CrownLoad(86, (unsigned long )0, 6, (long long )((char const   * __restrict  )"w"),
                  8);
      __CrownSetCallerCalleeName(87, "main", "fopen");
#line 10
      tmp___0 = fopen((char const   * __restrict  )"__SYM_assume_violated", (char const   * __restrict  )"w");
      __CrownEnableSymbolic(90, "main");
      __CrownHandleReturn(89, 6, (long long )tmp___0, 8);
      __CrownStore(88, (unsigned long )(& tmp___0));
      __CrownLoad(91, (unsigned long )(& tmp___0), 6, (long long )tmp___0, 8);
      __CrownStore(92, (unsigned long )(& f___0));
#line 10
      f___0 = tmp___0;
      {
      __CrownLoad(94, (unsigned long )(& f___0), 6, (long long )f___0, 8);
      __CrownApply1(93, 26, 5, (long long )(! f___0), (double )(! f___0));
#line 10
      if (! f___0) {
        __CrownBranch(95, 25, 1, __LINE__, __FILE__);
        __CrownLoad(98, (unsigned long )(& stderr), 6, (long long )stderr, 8);
        __CrownApply1(97, 27, 6, (long long )((FILE * __restrict  )stderr), 8);
        __CrownLoad(99, (unsigned long )0, 6, (long long )((char const   * __restrict  )"### %s file cannot be created ###\n"),
                    8);
        __CrownLoad(100, (unsigned long )0, 6, (long long )"__SYM_assume_violated",
                    8);
        __CrownSetCallerCalleeName(101, "main", "fprintf");
#line 10
        fprintf((FILE * __restrict  )stderr, (char const   * __restrict  )"### %s file cannot be created ###\n",
                "__SYM_assume_violated");
        __CrownEnableSymbolic(103, "main");
        __CrownClearStack(102);
      } 
        #line 10
        else {
        __CrownBranch(96, 26, 0, __LINE__, __FILE__);
        __CrownLoad(104, (unsigned long )(& f___0), 6, (long long )f___0, 8);
        __CrownSetCallerCalleeName(105, "main", "fclose");
#line 10
        fclose(f___0);
        __CrownEnableSymbolic(107, "main");
        __CrownClearStack(106);
      }
      }
      __CrownLoad(108, (unsigned long )0, 5, (long long )1, (double )1);
      __CrownSetCallerCalleeName(109, "main", "exit");
#line 10
      exit(1);
      __CrownEnableSymbolic(111, "main");
      __CrownClearStack(110);
    }
    }
#line 10
    goto while_break___0;
  }
  while_break___0: /* CIL Label */ ;
#line 11
  while (1) {
    while_continue___1: /* CIL Label */ ;
    {
    __CrownLoad(114, (unsigned long )0, 5, (long long )-10, (double )-10);
    __CrownLoad(113, (unsigned long )(& c), 5, (long long )c, (double )c);
    __CrownApply2(112, 20, 5, (long long )(-10 < c), (double )(-10 < c));
#line 11
    if (-10 < c) {
      __CrownBranch(115, 34, 1, __LINE__, __FILE__);
      {
      __CrownLoad(119, (unsigned long )(& c), 5, (long long )c, (double )c);
      __CrownLoad(118, (unsigned long )0, 5, (long long )10, (double )10);
      __CrownApply2(117, 20, 5, (long long )(c < 10), (double )(c < 10));
#line 11
      if (c < 10) {
        __CrownBranch(120, 35, 1, __LINE__, __FILE__);

      } 
        #line 11
        else {
        __CrownBranch(121, 36, 0, __LINE__, __FILE__);
#line 11
        goto _L___1;
      }
      }
    } 
      #line 11
      else {
      __CrownBranch(116, 37, 0, __LINE__, __FILE__);
      _L___1: /* CIL Label */ 
      __CrownLoad(123, (unsigned long )(& stderr), 6, (long long )stderr, 8);
      __CrownApply1(122, 27, 6, (long long )((FILE * __restrict  )stderr), 8);
      __CrownLoad(124, (unsigned long )0, 6, (long long )((char const   * __restrict  )"### SYM_assume(%s) is violated at Line %d (%s in %s) ###\n"),
                  8);
      __CrownLoad(125, (unsigned long )0, 6, (long long )"-10 < c && c < 10", 8);
      __CrownLoad(126, (unsigned long )0, 5, (long long )11, (double )11);
      __CrownLoad(127, (unsigned long )0, 6, (long long )"main", 8);
      __CrownLoad(128, (unsigned long )0, 6, (long long )"triangle.c", 8);
      __CrownSetCallerCalleeName(129, "main", "fprintf");
#line 11
      fprintf((FILE * __restrict  )stderr, (char const   * __restrict  )"### SYM_assume(%s) is violated at Line %d (%s in %s) ###\n",
              "-10 < c && c < 10", 11, "main", "triangle.c");
      __CrownEnableSymbolic(131, "main");
      __CrownClearStack(130);
      __CrownLoad(132, (unsigned long )0, 6, (long long )((char const   * __restrict  )"__SYM_assume_violated"),
                  8);
      __CrownLoad(133, (unsigned long )0, 6, (long long )((char const   * __restrict  )"w"),
                  8);
      __CrownSetCallerCalleeName(134, "main", "fopen");
#line 11
      tmp___1 = fopen((char const   * __restrict  )"__SYM_assume_violated", (char const   * __restrict  )"w");
      __CrownEnableSymbolic(137, "main");
      __CrownHandleReturn(136, 6, (long long )tmp___1, 8);
      __CrownStore(135, (unsigned long )(& tmp___1));
      __CrownLoad(138, (unsigned long )(& tmp___1), 6, (long long )tmp___1, 8);
      __CrownStore(139, (unsigned long )(& f___1));
#line 11
      f___1 = tmp___1;
      {
      __CrownLoad(141, (unsigned long )(& f___1), 6, (long long )f___1, 8);
      __CrownApply1(140, 26, 5, (long long )(! f___1), (double )(! f___1));
#line 11
      if (! f___1) {
        __CrownBranch(142, 39, 1, __LINE__, __FILE__);
        __CrownLoad(145, (unsigned long )(& stderr), 6, (long long )stderr, 8);
        __CrownApply1(144, 27, 6, (long long )((FILE * __restrict  )stderr), 8);
        __CrownLoad(146, (unsigned long )0, 6, (long long )((char const   * __restrict  )"### %s file cannot be created ###\n"),
                    8);
        __CrownLoad(147, (unsigned long )0, 6, (long long )"__SYM_assume_violated",
                    8);
        __CrownSetCallerCalleeName(148, "main", "fprintf");
#line 11
        fprintf((FILE * __restrict  )stderr, (char const   * __restrict  )"### %s file cannot be created ###\n",
                "__SYM_assume_violated");
        __CrownEnableSymbolic(150, "main");
        __CrownClearStack(149);
      } 
        #line 11
        else {
        __CrownBranch(143, 40, 0, __LINE__, __FILE__);
        __CrownLoad(151, (unsigned long )(& f___1), 6, (long long )f___1, 8);
        __CrownSetCallerCalleeName(152, "main", "fclose");
#line 11
        fclose(f___1);
        __CrownEnableSymbolic(154, "main");
        __CrownClearStack(153);
      }
      }
      __CrownLoad(155, (unsigned long )0, 5, (long long )1, (double )1);
      __CrownSetCallerCalleeName(156, "main", "exit");
#line 11
      exit(1);
      __CrownEnableSymbolic(158, "main");
      __CrownClearStack(157);
    }
    }
#line 11
    goto while_break___1;
  }
  while_break___1: /* CIL Label */ 
  __CrownLoad(159, (unsigned long )0, 6, (long long )((char const   * __restrict  )"a,b,c = %d,%d,%d\n"),
              8);
  __CrownLoad(160, (unsigned long )(& a), 5, (long long )a, (double )a);
  __CrownLoad(161, (unsigned long )(& b), 5, (long long )b, (double )b);
  __CrownLoad(162, (unsigned long )(& c), 5, (long long )c, (double )c);
  __CrownSetCallerCalleeName(163, "main", "printf");
#line 20
  printf((char const   * __restrict  )"a,b,c = %d,%d,%d\n", a, b, c);
  __CrownEnableSymbolic(165, "main");
  __CrownClearStack(164);
  __CrownLoad(166, (unsigned long )0, 5, (long long )-1, (double )-1);
  __CrownStore(167, (unsigned long )(& result));
#line 24
  result = -1;
  __CrownLoad(170, (unsigned long )(& a), 5, (long long )a, (double )a);
  __CrownLoad(169, (unsigned long )(& b), 5, (long long )b, (double )b);
  __CrownApply2(168, 13, 5, (long long )(a == b), (double )(a == b));
#line 25
  if (a == b) {
    __CrownBranch(171, 46, 1, __LINE__, __FILE__);
    __CrownLoad(175, (unsigned long )(& match), 5, (long long )match, (double )match);
    __CrownLoad(174, (unsigned long )0, 5, (long long )1, (double )1);
    __CrownApply2(173, 0, 5, (long long )(match + 1), (double )(match + 1));
    __CrownStore(176, (unsigned long )(& match));
#line 25
    match ++;
  } 
    #line 25
    else {
    __CrownBranch(172, 47, 0, __LINE__, __FILE__);

  }
  __CrownLoad(179, (unsigned long )(& a), 5, (long long )a, (double )a);
  __CrownLoad(178, (unsigned long )(& c), 5, (long long )c, (double )c);
  __CrownApply2(177, 13, 5, (long long )(a == c), (double )(a == c));
#line 26
  if (a == c) {
    __CrownBranch(180, 49, 1, __LINE__, __FILE__);
    __CrownLoad(184, (unsigned long )(& match), 5, (long long )match, (double )match);
    __CrownLoad(183, (unsigned long )0, 5, (long long )2, (double )2);
    __CrownApply2(182, 0, 5, (long long )(match + 2), (double )(match + 2));
    __CrownStore(185, (unsigned long )(& match));
#line 26
    match += 2;
  } 
    #line 26
    else {
    __CrownBranch(181, 50, 0, __LINE__, __FILE__);

  }
  __CrownLoad(188, (unsigned long )(& b), 5, (long long )b, (double )b);
  __CrownLoad(187, (unsigned long )(& c), 5, (long long )c, (double )c);
  __CrownApply2(186, 13, 5, (long long )(b == c), (double )(b == c));
#line 27
  if (b == c) {
    __CrownBranch(189, 52, 1, __LINE__, __FILE__);
    __CrownLoad(193, (unsigned long )(& match), 5, (long long )match, (double )match);
    __CrownLoad(192, (unsigned long )0, 5, (long long )3, (double )3);
    __CrownApply2(191, 0, 5, (long long )(match + 3), (double )(match + 3));
    __CrownStore(194, (unsigned long )(& match));
#line 27
    match += 3;
  } 
    #line 27
    else {
    __CrownBranch(190, 53, 0, __LINE__, __FILE__);

  }
  __CrownLoad(197, (unsigned long )(& match), 5, (long long )match, (double )match);
  __CrownLoad(196, (unsigned long )0, 5, (long long )0, (double )0);
  __CrownApply2(195, 13, 5, (long long )(match == 0), (double )(match == 0));
#line 28
  if (match == 0) {
    __CrownBranch(198, 55, 1, __LINE__, __FILE__);
    {
    __CrownLoad(204, (unsigned long )(& a), 5, (long long )a, (double )a);
    __CrownLoad(203, (unsigned long )(& b), 5, (long long )b, (double )b);
    __CrownApply2(202, 0, 5, (long long )(a + b), (double )(a + b));
    __CrownLoad(201, (unsigned long )(& c), 5, (long long )c, (double )c);
    __CrownApply2(200, 18, 5, (long long )(a + b <= c), (double )(a + b <= c));
#line 29
    if (a + b <= c) {
      __CrownBranch(205, 56, 1, __LINE__, __FILE__);
      __CrownLoad(207, (unsigned long )0, 5, (long long )2, (double )2);
      __CrownStore(208, (unsigned long )(& result));
#line 29
      result = 2;
    } 
      #line 29
      else {
      __CrownBranch(206, 57, 0, __LINE__, __FILE__);
      {
      __CrownLoad(213, (unsigned long )(& b), 5, (long long )b, (double )b);
      __CrownLoad(212, (unsigned long )(& c), 5, (long long )c, (double )c);
      __CrownApply2(211, 0, 5, (long long )(b + c), (double )(b + c));
      __CrownLoad(210, (unsigned long )(& a), 5, (long long )a, (double )a);
      __CrownApply2(209, 18, 5, (long long )(b + c <= a), (double )(b + c <= a));
#line 30
      if (b + c <= a) {
        __CrownBranch(214, 58, 1, __LINE__, __FILE__);
        __CrownLoad(216, (unsigned long )0, 5, (long long )2, (double )2);
        __CrownStore(217, (unsigned long )(& result));
#line 30
        result = 2;
      } 
        #line 30
        else {
        __CrownBranch(215, 59, 0, __LINE__, __FILE__);
        {
        __CrownLoad(222, (unsigned long )(& a), 5, (long long )a, (double )a);
        __CrownLoad(221, (unsigned long )(& c), 5, (long long )c, (double )c);
        __CrownApply2(220, 0, 5, (long long )(a + c), (double )(a + c));
        __CrownLoad(219, (unsigned long )(& b), 5, (long long )b, (double )b);
        __CrownApply2(218, 18, 5, (long long )(a + c <= b), (double )(a + c <= b));
#line 31
        if (a + c <= b) {
          __CrownBranch(223, 60, 1, __LINE__, __FILE__);
          __CrownLoad(225, (unsigned long )0, 5, (long long )2, (double )2);
          __CrownStore(226, (unsigned long )(& result));
#line 31
          result = 2;
        } 
          #line 31
          else {
          __CrownBranch(224, 61, 0, __LINE__, __FILE__);
          __CrownLoad(227, (unsigned long )0, 5, (long long )3, (double )3);
          __CrownStore(228, (unsigned long )(& result));
#line 32
          result = 3;
        }
        }
      }
      }
    }
    }
  } 
    #line 28
    else {
    __CrownBranch(199, 62, 0, __LINE__, __FILE__);
    {
    __CrownLoad(231, (unsigned long )(& match), 5, (long long )match, (double )match);
    __CrownLoad(230, (unsigned long )0, 5, (long long )1, (double )1);
    __CrownApply2(229, 13, 5, (long long )(match == 1), (double )(match == 1));
#line 34
    if (match == 1) {
      __CrownBranch(232, 63, 1, __LINE__, __FILE__);
      {
      __CrownLoad(238, (unsigned long )(& a), 5, (long long )a, (double )a);
      __CrownLoad(237, (unsigned long )(& b), 5, (long long )b, (double )b);
      __CrownApply2(236, 0, 5, (long long )(a + b), (double )(a + b));
      __CrownLoad(235, (unsigned long )(& c), 5, (long long )c, (double )c);
      __CrownApply2(234, 18, 5, (long long )(a + b <= c), (double )(a + b <= c));
#line 35
      if (a + b <= c) {
        __CrownBranch(239, 64, 1, __LINE__, __FILE__);
        __CrownLoad(241, (unsigned long )0, 5, (long long )2, (double )2);
        __CrownStore(242, (unsigned long )(& result));
#line 35
        result = 2;
      } 
        #line 35
        else {
        __CrownBranch(240, 65, 0, __LINE__, __FILE__);
        __CrownLoad(243, (unsigned long )0, 5, (long long )1, (double )1);
        __CrownStore(244, (unsigned long )(& result));
#line 36
        result = 1;
      }
      }
    } 
      #line 34
      else {
      __CrownBranch(233, 66, 0, __LINE__, __FILE__);
      {
      __CrownLoad(247, (unsigned long )(& match), 5, (long long )match, (double )match);
      __CrownLoad(246, (unsigned long )0, 5, (long long )2, (double )2);
      __CrownApply2(245, 13, 5, (long long )(match == 2), (double )(match == 2));
#line 38
      if (match == 2) {
        __CrownBranch(248, 67, 1, __LINE__, __FILE__);
        {
        __CrownLoad(254, (unsigned long )(& a), 5, (long long )a, (double )a);
        __CrownLoad(253, (unsigned long )(& c), 5, (long long )c, (double )c);
        __CrownApply2(252, 0, 5, (long long )(a + c), (double )(a + c));
        __CrownLoad(251, (unsigned long )(& b), 5, (long long )b, (double )b);
        __CrownApply2(250, 18, 5, (long long )(a + c <= b), (double )(a + c <= b));
#line 39
        if (a + c <= b) {
          __CrownBranch(255, 68, 1, __LINE__, __FILE__);
          __CrownLoad(257, (unsigned long )0, 5, (long long )2, (double )2);
          __CrownStore(258, (unsigned long )(& result));
#line 39
          result = 2;
        } 
          #line 39
          else {
          __CrownBranch(256, 69, 0, __LINE__, __FILE__);
          __CrownLoad(259, (unsigned long )0, 5, (long long )1, (double )1);
          __CrownStore(260, (unsigned long )(& result));
#line 40
          result = 1;
        }
        }
      } 
        #line 38
        else {
        __CrownBranch(249, 70, 0, __LINE__, __FILE__);
        {
        __CrownLoad(263, (unsigned long )(& match), 5, (long long )match, (double )match);
        __CrownLoad(262, (unsigned long )0, 5, (long long )3, (double )3);
        __CrownApply2(261, 13, 5, (long long )(match == 3), (double )(match == 3));
#line 42
        if (match == 3) {
          __CrownBranch(264, 71, 1, __LINE__, __FILE__);
          {
          __CrownLoad(270, (unsigned long )(& b), 5, (long long )b, (double )b);
          __CrownLoad(269, (unsigned long )(& c), 5, (long long )c, (double )c);
          __CrownApply2(268, 0, 5, (long long )(b + c), (double )(b + c));
          __CrownLoad(267, (unsigned long )(& a), 5, (long long )a, (double )a);
          __CrownApply2(266, 18, 5, (long long )(b + c <= a), (double )(b + c <= a));
#line 43
          if (b + c <= a) {
            __CrownBranch(271, 72, 1, __LINE__, __FILE__);
            __CrownLoad(273, (unsigned long )0, 5, (long long )2, (double )2);
            __CrownStore(274, (unsigned long )(& result));
#line 43
            result = 2;
          } 
            #line 43
            else {
            __CrownBranch(272, 73, 0, __LINE__, __FILE__);
            __CrownLoad(275, (unsigned long )0, 5, (long long )1, (double )1);
            __CrownStore(276, (unsigned long )(& result));
#line 44
            result = 1;
          }
          }
        } 
          #line 42
          else {
          __CrownBranch(265, 74, 0, __LINE__, __FILE__);
          __CrownLoad(277, (unsigned long )0, 5, (long long )0, (double )0);
          __CrownStore(278, (unsigned long )(& result));
#line 45
          result = 0;
        }
        }
      }
      }
    }
    }
  }
  __CrownLoad(281, (unsigned long )(& result), 5, (long long )result, (double )result);
  __CrownLoad(280, (unsigned long )0, 5, (long long )0, (double )0);
  __CrownApply2(279, 13, 5, (long long )(result == 0), (double )(result == 0));
#line 50
  if (result == 0) {
    __CrownBranch(282, 77, 1, __LINE__, __FILE__);
#line 50
    goto case_0;
  } 
    #line 50
    else {
    __CrownBranch(283, 78, 0, __LINE__, __FILE__);

  }
  __CrownLoad(286, (unsigned long )(& result), 5, (long long )result, (double )result);
  __CrownLoad(285, (unsigned long )0, 5, (long long )1, (double )1);
  __CrownApply2(284, 13, 5, (long long )(result == 1), (double )(result == 1));
#line 51
  if (result == 1) {
    __CrownBranch(287, 80, 1, __LINE__, __FILE__);
#line 51
    goto case_1;
  } 
    #line 51
    else {
    __CrownBranch(288, 81, 0, __LINE__, __FILE__);

  }
  __CrownLoad(291, (unsigned long )(& result), 5, (long long )result, (double )result);
  __CrownLoad(290, (unsigned long )0, 5, (long long )2, (double )2);
  __CrownApply2(289, 13, 5, (long long )(result == 2), (double )(result == 2));
#line 52
  if (result == 2) {
    __CrownBranch(292, 83, 1, __LINE__, __FILE__);
#line 52
    goto case_2;
  } 
    #line 52
    else {
    __CrownBranch(293, 84, 0, __LINE__, __FILE__);

  }
  __CrownLoad(296, (unsigned long )(& result), 5, (long long )result, (double )result);
  __CrownLoad(295, (unsigned long )0, 5, (long long )3, (double )3);
  __CrownApply2(294, 13, 5, (long long )(result == 3), (double )(result == 3));
#line 53
  if (result == 3) {
    __CrownBranch(297, 86, 1, __LINE__, __FILE__);
#line 53
    goto case_3;
  } 
    #line 53
    else {
    __CrownBranch(298, 87, 0, __LINE__, __FILE__);

  }
#line 49
  goto switch_break;
  case_0: /* CIL Label */ 
  __CrownLoad(300, (unsigned long )0, 6, (long long )(triangle_type), 8);
  __CrownApply1(299, 27, 6, (long long )((char * __restrict  )(triangle_type)), 8);
  __CrownLoad(301, (unsigned long )0, 6, (long long )((char const   * __restrict  )"an equilateral"),
              8);
  __CrownSetCallerCalleeName(302, "main", "strcpy");
#line 50
  strcpy((char * __restrict  )(triangle_type), (char const   * __restrict  )"an equilateral");
  __CrownEnableSymbolic(304, "main");
  __CrownClearStack(303);
#line 50
  goto switch_break;
  case_1: /* CIL Label */ 
  __CrownLoad(306, (unsigned long )0, 6, (long long )(triangle_type), 8);
  __CrownApply1(305, 27, 6, (long long )((char * __restrict  )(triangle_type)), 8);
  __CrownLoad(307, (unsigned long )0, 6, (long long )((char const   * __restrict  )"an isoscele"),
              8);
  __CrownSetCallerCalleeName(308, "main", "strcpy");
#line 51
  strcpy((char * __restrict  )(triangle_type), (char const   * __restrict  )"an isoscele");
  __CrownEnableSymbolic(310, "main");
  __CrownClearStack(309);
#line 51
  goto switch_break;
  case_2: /* CIL Label */ 
  __CrownLoad(312, (unsigned long )0, 6, (long long )(triangle_type), 8);
  __CrownApply1(311, 27, 6, (long long )((char * __restrict  )(triangle_type)), 8);
  __CrownLoad(313, (unsigned long )0, 6, (long long )((char const   * __restrict  )"not a triangle"),
              8);
  __CrownSetCallerCalleeName(314, "main", "strcpy");
#line 52
  strcpy((char * __restrict  )(triangle_type), (char const   * __restrict  )"not a triangle");
  __CrownEnableSymbolic(316, "main");
  __CrownClearStack(315);
#line 52
  goto switch_break;
  case_3: /* CIL Label */ 
  __CrownLoad(318, (unsigned long )0, 6, (long long )(triangle_type), 8);
  __CrownApply1(317, 27, 6, (long long )((char * __restrict  )(triangle_type)), 8);
  __CrownLoad(319, (unsigned long )0, 6, (long long )((char const   * __restrict  )"a scalene"),
              8);
  __CrownSetCallerCalleeName(320, "main", "strcpy");
#line 53
  strcpy((char * __restrict  )(triangle_type), (char const   * __restrict  )"a scalene");
  __CrownEnableSymbolic(322, "main");
  __CrownClearStack(321);
#line 53
  goto switch_break;
#line 54
  goto switch_break;
  switch_break: /* CIL Label */ 
  __CrownLoad(323, (unsigned long )0, 6, (long long )((char const   * __restrict  )"This triangle is %s.\n"),
              8);
  __CrownLoad(324, (unsigned long )0, 6, (long long )(triangle_type), 8);
  __CrownSetCallerCalleeName(325, "main", "printf");
#line 56
  printf((char const   * __restrict  )"This triangle is %s.\n", triangle_type);
  __CrownEnableSymbolic(327, "main");
  __CrownClearStack(326);
  __CrownLoad(328, (unsigned long )0, 5, (long long )0, (double )0);
  __CrownStore(329, (unsigned long )(& __retres13));
#line 57
  __retres13 = 0;
  __CrownLoad(330, (unsigned long )(& __retres13), 5, (long long )__retres13, (double )__retres13);
  __CrownReturn(331);
#line 6
  return (__retres13);
}
}
void __globinit_triangle(void) 
{ 


  {
  __CrownInit(332);
}
}
