/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is true */

#line 79 "bin-search-crown.c"
void __globinit_bin_search_crown(void) ;
extern void __CrownInit(int id )  __attribute__((__crown_skip__)) ;
extern void __CrownHandleReturn(int id , int type , long long val , double fp_val )  __attribute__((__crown_skip__)) ;
extern void __CrownReturn(int id )  __attribute__((__crown_skip__)) ;
extern void __CrownCall(int id , unsigned int fid )  __attribute__((__crown_skip__)) ;
extern void __CrownBranch(int id , int bid , unsigned char b , int line , char *fname )  __attribute__((__crown_skip__)) ;
extern void __CrownApply2(int id , int op , int type , long long val , double fp_val )  __attribute__((__crown_skip__)) ;
extern void __CrownApply1(int id , int op , int type , long long val , double fp_val )  __attribute__((__crown_skip__)) ;
extern void __CrownClearStack(int id )  __attribute__((__crown_skip__)) ;
extern void __CrownStore(int id , unsigned long addr )  __attribute__((__crown_skip__)) ;
extern void __CrownLoad(int id , unsigned long addr , int type , long long val , double fp_val ,
                        char *name , int cnt_symbolic_var , char highestBit , char lowestBit )  __attribute__((__crown_skip__)) ;
unsigned long __CrownTempCall  ;
unsigned long __CrownTempAssign  ;
#line 362 "/usr/include/stdio.h"
extern int printf(char const   * __restrict  __format  , ...) ;
#line 69 "/usr/include/assert.h"
extern  __attribute__((__nothrow__, __noreturn__)) void ( __attribute__((__leaf__)) __assert_fail)(char const   *__assertion ,
                                                                                                   char const   *__file ,
                                                                                                   unsigned int __line ,
                                                                                                   char const   *__function ) ;
#line 543 "/usr/include/stdlib.h"
extern  __attribute__((__nothrow__, __noreturn__)) void ( __attribute__((__leaf__)) exit)(int __status ) ;
#line 312 "/home/moonzoo/CROWN/bin/../include/crown.h"
extern void __CrownInt(int *x , int cnt_sym_var , int ln , char *fname  , ...)  __attribute__((__crown_skip__)) ;
#line 8 "bin-search-crown.c"
int array[8]  ;
#line 8 "bin-search-crown.c"
int n  ;
#line 9 "bin-search-crown.c"
int old_array[8]  ;
#line 17
void setup_array(void) ;
#line 17 "bin-search-crown.c"
static int cnt_symbolic_var  =    1;
#line 27
void setup_array(void) ;
#line 27 "bin-search-crown.c"
static int cnt_symbolic_var___0  =    1;
#line 11 "bin-search-crown.c"
void setup_array(void) 
{ 
  int c ;

  {
  __CrownCall(1, 1);

#line 17
  __CrownInt(& n, cnt_symbolic_var, 17, (char *)"bin-search-crown.c", "n");
  __CrownLoad(4, (unsigned long )(& cnt_symbolic_var), 5, (long long )cnt_symbolic_var,
              (double )cnt_symbolic_var, (char *)"", 0, (char)0, (char)0);
  __CrownLoad(3, (unsigned long )0, 5, (long long )1, (double )1, (char *)"", 0, (char)0,
              (char)0);
  __CrownApply2(2, 0, 5, (long long )(cnt_symbolic_var + 1), (double )(cnt_symbolic_var + 1));
  __CrownStore(5, (unsigned long )(& cnt_symbolic_var));
#line 17
  cnt_symbolic_var ++;
  {
  __CrownLoad(8, (unsigned long )0, 5, (long long )0, (double )0, (char *)"", 0, (char)0,
              (char)0);
  __CrownLoad(7, (unsigned long )(& n), 5, (long long )n, (double )n, (char *)"",
              0, (char)0, (char)0);
  __CrownApply2(6, 20, 5, (long long )(0 < n), (double )(0 < n));
#line 20
  if (0 < n) {
    __CrownBranch(9, 3, 1, __LINE__, __FILE__);
    {
    __CrownLoad(13, (unsigned long )(& n), 5, (long long )n, (double )n, (char *)"",
                0, (char)0, (char)0);
    __CrownLoad(12, (unsigned long )0, 5, (long long )8, (double )8, (char *)"", 0,
                (char)0, (char)0);
    __CrownApply2(11, 18, 5, (long long )(n <= 8), (double )(n <= 8));
#line 20
    if (n <= 8) {
      __CrownBranch(14, 4, 1, __LINE__, __FILE__);

    } 
      #line 20
      else {
      __CrownBranch(15, 5, 0, __LINE__, __FILE__);
      __CrownLoad(16, (unsigned long )0, 6, (long long )((char const   * __restrict  )"Invalid input generated:n=%d\n"),
                  8, (char *)"", 0, (char)0, (char)0);
      __CrownLoad(17, (unsigned long )(& n), 5, (long long )n, (double )n, (char *)"",
                  0, (char)0, (char)0);
#line 20
      printf((char const   * __restrict  )"Invalid input generated:n=%d\n", n);
      __CrownClearStack(18);
      __CrownLoad(19, (unsigned long )0, 5, (long long )-1, (double )-1, (char *)"",
                  0, (char)0, (char)0);
#line 20
      exit(-1);
      __CrownClearStack(20);
    }
    }
  } 
    #line 20
    else {
    __CrownBranch(10, 6, 0, __LINE__, __FILE__);
    __CrownLoad(21, (unsigned long )0, 6, (long long )((char const   * __restrict  )"Invalid input generated:n=%d\n"),
                8, (char *)"", 0, (char)0, (char)0);
    __CrownLoad(22, (unsigned long )(& n), 5, (long long )n, (double )n, (char *)"",
                0, (char)0, (char)0);
#line 20
    printf((char const   * __restrict  )"Invalid input generated:n=%d\n", n);
    __CrownClearStack(23);
    __CrownLoad(24, (unsigned long )0, 5, (long long )-1, (double )-1, (char *)"",
                0, (char)0, (char)0);
#line 20
    exit(-1);
    __CrownClearStack(25);
  }
  }
  __CrownLoad(26, (unsigned long )0, 5, (long long )0, (double )0, (char *)"", 0,
              (char)0, (char)0);
  __CrownStore(27, (unsigned long )(& c));
#line 24
  c = 0;
  {
#line 24
  while (1) {
    while_continue: /* CIL Label */ ;
    {
    __CrownLoad(30, (unsigned long )(& c), 5, (long long )c, (double )c, (char *)"",
                0, (char)0, (char)0);
    __CrownLoad(29, (unsigned long )(& n), 5, (long long )n, (double )n, (char *)"",
                0, (char)0, (char)0);
    __CrownApply2(28, 20, 5, (long long )(c < n), (double )(c < n));
#line 24
    if (c < n) {
      __CrownBranch(31, 12, 1, __LINE__, __FILE__);

    } 
      #line 24
      else {
      __CrownBranch(32, 13, 0, __LINE__, __FILE__);
#line 24
      goto while_break;
    }
    }
#line 27
    __CrownInt(& array[c], cnt_symbolic_var___0, 27, (char *)"bin-search-crown.c",
               "array[c]");
    __CrownLoad(35, (unsigned long )(& cnt_symbolic_var___0), 5, (long long )cnt_symbolic_var___0,
                (double )cnt_symbolic_var___0, (char *)"", 0, (char)0, (char)0);
    __CrownLoad(34, (unsigned long )0, 5, (long long )1, (double )1, (char *)"", 0,
                (char)0, (char)0);
    __CrownApply2(33, 0, 5, (long long )(cnt_symbolic_var___0 + 1), (double )(cnt_symbolic_var___0 + 1));
    __CrownStore(36, (unsigned long )(& cnt_symbolic_var___0));
#line 27
    cnt_symbolic_var___0 ++;
    {
    __CrownLoad(39, (unsigned long )(& c), 5, (long long )c, (double )c, (char *)"",
                0, (char)0, (char)0);
    __CrownLoad(38, (unsigned long )0, 5, (long long )0, (double )0, (char *)"", 0,
                (char)0, (char)0);
    __CrownApply2(37, 16, 5, (long long )(c > 0), (double )(c > 0));
#line 28
    if (c > 0) {
      __CrownBranch(40, 16, 1, __LINE__, __FILE__);
      {
      __CrownLoad(45, (unsigned long )(& array[c - 1]), 5, (long long )array[c - 1],
                  (double )array[c - 1], (char *)"", 0, (char)0, (char)0);
      __CrownLoad(44, (unsigned long )(& array[c]), 5, (long long )array[c], (double )array[c],
                  (char *)"", 0, (char)0, (char)0);
      __CrownApply2(43, 18, 5, (long long )(array[c - 1] <= array[c]), (double )(array[c - 1] <= array[c]));
      __CrownApply1(42, 26, 5, (long long )(! (array[c - 1] <= array[c])), (double )(! (array[c - 1] <= array[c])));
#line 30
      if (! (array[c - 1] <= array[c])) {
        __CrownBranch(46, 17, 1, __LINE__, __FILE__);
        __CrownLoad(48, (unsigned long )0, 6, (long long )((char const   * __restrict  )"Invalid input generated:a[%d]=%d\n"),
                    8, (char *)"", 0, (char)0, (char)0);
        __CrownLoad(49, (unsigned long )(& c), 5, (long long )c, (double )c, (char *)"",
                    0, (char)0, (char)0);
        __CrownLoad(50, (unsigned long )(& array[c]), 5, (long long )array[c], (double )array[c],
                    (char *)"", 0, (char)0, (char)0);
#line 30
        printf((char const   * __restrict  )"Invalid input generated:a[%d]=%d\n",
               c, array[c]);
        __CrownClearStack(51);
        __CrownLoad(52, (unsigned long )0, 5, (long long )-1, (double )-1, (char *)"",
                    0, (char)0, (char)0);
#line 30
        exit(-1);
        __CrownClearStack(53);
      } 
        #line 30
        else {
        __CrownBranch(47, 18, 0, __LINE__, __FILE__);

      }
      }
    } 
      #line 28
      else {
      __CrownBranch(41, 19, 0, __LINE__, __FILE__);

    }
    }
    __CrownLoad(56, (unsigned long )(& c), 5, (long long )c, (double )c, (char *)"",
                0, (char)0, (char)0);
    __CrownLoad(55, (unsigned long )0, 5, (long long )1, (double )1, (char *)"", 0,
                (char)0, (char)0);
    __CrownApply2(54, 0, 5, (long long )(c + 1), (double )(c + 1));
    __CrownStore(57, (unsigned long )(& c));
#line 24
    c ++;
  }
  while_break: /* CIL Label */ ;
  }

  {
  __CrownReturn(58);
#line 11
  return;
  }
}
}
#line 37 "bin-search-crown.c"
int bin_search(int search ) 
{ 
  int first ;
  int last ;
  int middle ;
  int __retres5 ;

  {
  __CrownCall(60, 2);
  __CrownStore(59, (unsigned long )(& search));
  __CrownLoad(61, (unsigned long )0, 5, (long long )0, (double )0, (char *)"", 0,
              (char)0, (char)0);
  __CrownStore(62, (unsigned long )(& first));
#line 41
  first = 0;
  __CrownLoad(65, (unsigned long )(& n), 5, (long long )n, (double )n, (char *)"",
              0, (char)0, (char)0);
  __CrownLoad(64, (unsigned long )0, 5, (long long )1, (double )1, (char *)"", 0,
              (char)0, (char)0);
  __CrownApply2(63, 1, 5, (long long )(n - 1), (double )(n - 1));
  __CrownStore(66, (unsigned long )(& last));
#line 42
  last = n - 1;
  __CrownLoad(71, (unsigned long )(& first), 5, (long long )first, (double )first,
              (char *)"", 0, (char)0, (char)0);
  __CrownLoad(70, (unsigned long )(& last), 5, (long long )last, (double )last, (char *)"",
              0, (char)0, (char)0);
  __CrownApply2(69, 0, 5, (long long )(first + last), (double )(first + last));
  __CrownLoad(68, (unsigned long )0, 5, (long long )2, (double )2, (char *)"", 0,
              (char)0, (char)0);
  __CrownApply2(67, 4, 5, (long long )((first + last) / 2), (double )((first + last) / 2));
  __CrownStore(72, (unsigned long )(& middle));
#line 43
  middle = (first + last) / 2;
  {
#line 45
  while (1) {
    while_continue: /* CIL Label */ ;
    {
    __CrownLoad(75, (unsigned long )(& first), 5, (long long )first, (double )first,
                (char *)"", 0, (char)0, (char)0);
    __CrownLoad(74, (unsigned long )(& last), 5, (long long )last, (double )last,
                (char *)"", 0, (char)0, (char)0);
    __CrownApply2(73, 18, 5, (long long )(first <= last), (double )(first <= last));
#line 45
    if (first <= last) {
      __CrownBranch(76, 29, 1, __LINE__, __FILE__);

    } 
      #line 45
      else {
      __CrownBranch(77, 30, 0, __LINE__, __FILE__);
#line 45
      goto while_break;
    }
    }
    {
    __CrownLoad(80, (unsigned long )(& array[middle]), 5, (long long )array[middle],
                (double )array[middle], (char *)"", 0, (char)0, (char)0);
    __CrownLoad(79, (unsigned long )(& search), 5, (long long )search, (double )search,
                (char *)"", 0, (char)0, (char)0);
    __CrownApply2(78, 20, 5, (long long )(array[middle] < search), (double )(array[middle] < search));
#line 46
    if (array[middle] < search) {
      __CrownBranch(81, 32, 1, __LINE__, __FILE__);
      __CrownLoad(85, (unsigned long )(& middle), 5, (long long )middle, (double )middle,
                  (char *)"", 0, (char)0, (char)0);
      __CrownLoad(84, (unsigned long )0, 5, (long long )1, (double )1, (char *)"",
                  0, (char)0, (char)0);
      __CrownApply2(83, 0, 5, (long long )(middle + 1), (double )(middle + 1));
      __CrownStore(86, (unsigned long )(& first));
#line 47
      first = middle + 1;
    } 
      #line 46
      else {
      __CrownBranch(82, 33, 0, __LINE__, __FILE__);
      {
      __CrownLoad(89, (unsigned long )(& array[middle]), 5, (long long )array[middle],
                  (double )array[middle], (char *)"", 0, (char)0, (char)0);
      __CrownLoad(88, (unsigned long )(& search), 5, (long long )search, (double )search,
                  (char *)"", 0, (char)0, (char)0);
      __CrownApply2(87, 13, 5, (long long )(array[middle] == search), (double )(array[middle] == search));
#line 48
      if (array[middle] == search) {
        __CrownBranch(90, 34, 1, __LINE__, __FILE__);
        __CrownLoad(92, (unsigned long )(& middle), 5, (long long )middle, (double )middle,
                    (char *)"", 0, (char)0, (char)0);
        __CrownStore(93, (unsigned long )(& __retres5));
#line 50
        __retres5 = middle;
#line 50
        goto return_label;
      } 
        #line 48
        else {
        __CrownBranch(91, 36, 0, __LINE__, __FILE__);
        __CrownLoad(96, (unsigned long )(& middle), 5, (long long )middle, (double )middle,
                    (char *)"", 0, (char)0, (char)0);
        __CrownLoad(95, (unsigned long )0, 5, (long long )1, (double )1, (char *)"",
                    0, (char)0, (char)0);
        __CrownApply2(94, 1, 5, (long long )(middle - 1), (double )(middle - 1));
        __CrownStore(97, (unsigned long )(& last));
#line 53
        last = middle - 1;
      }
      }
    }
    }
    __CrownLoad(102, (unsigned long )(& first), 5, (long long )first, (double )first,
                (char *)"", 0, (char)0, (char)0);
    __CrownLoad(101, (unsigned long )(& last), 5, (long long )last, (double )last,
                (char *)"", 0, (char)0, (char)0);
    __CrownApply2(100, 0, 5, (long long )(first + last), (double )(first + last));
    __CrownLoad(99, (unsigned long )0, 5, (long long )2, (double )2, (char *)"", 0,
                (char)0, (char)0);
    __CrownApply2(98, 4, 5, (long long )((first + last) / 2), (double )((first + last) / 2));
    __CrownStore(103, (unsigned long )(& middle));
#line 55
    middle = (first + last) / 2;
  }
  while_break: /* CIL Label */ ;
  }
  __CrownLoad(104, (unsigned long )0, 5, (long long )-1, (double )-1, (char *)"",
              0, (char)0, (char)0);
  __CrownStore(105, (unsigned long )(& __retres5));
#line 57
  __retres5 = -1;
  return_label: /* CIL Label */ 
  {
  __CrownLoad(106, (unsigned long )(& __retres5), 5, (long long )__retres5, (double )__retres5,
              (char *)"", 0, (char)0, (char)0);
  __CrownReturn(107);
#line 37
  return (__retres5);
  }
}
}
#line 61 "bin-search-crown.c"
int check(int idx , int search ) 
{ 
  int i ;
  int __retres5 ;

  {
  __CrownCall(110, 3);
  __CrownStore(109, (unsigned long )(& search));
  __CrownStore(108, (unsigned long )(& idx));
  {
  __CrownLoad(113, (unsigned long )(& idx), 5, (long long )idx, (double )idx, (char *)"",
              0, (char)0, (char)0);
  __CrownLoad(112, (unsigned long )0, 5, (long long )-1, (double )-1, (char *)"",
              0, (char)0, (char)0);
  __CrownApply2(111, 13, 5, (long long )(idx == -1), (double )(idx == -1));
#line 63
  if (idx == -1) {
    __CrownBranch(114, 42, 1, __LINE__, __FILE__);
    __CrownLoad(116, (unsigned long )0, 5, (long long )0, (double )0, (char *)"",
                0, (char)0, (char)0);
    __CrownStore(117, (unsigned long )(& i));
#line 64
    i = 0;
    {
#line 64
    while (1) {
      while_continue: /* CIL Label */ ;
      {
      __CrownLoad(120, (unsigned long )(& i), 5, (long long )i, (double )i, (char *)"",
                  0, (char)0, (char)0);
      __CrownLoad(119, (unsigned long )(& n), 5, (long long )n, (double )n, (char *)"",
                  0, (char)0, (char)0);
      __CrownApply2(118, 20, 5, (long long )(i < n), (double )(i < n));
#line 64
      if (i < n) {
        __CrownBranch(121, 47, 1, __LINE__, __FILE__);

      } 
        #line 64
        else {
        __CrownBranch(122, 48, 0, __LINE__, __FILE__);
#line 64
        goto while_break;
      }
      }
      {
      __CrownLoad(125, (unsigned long )(& array[i]), 5, (long long )array[i], (double )array[i],
                  (char *)"", 0, (char)0, (char)0);
      __CrownLoad(124, (unsigned long )(& search), 5, (long long )search, (double )search,
                  (char *)"", 0, (char)0, (char)0);
      __CrownApply2(123, 13, 5, (long long )(array[i] == search), (double )(array[i] == search));
#line 65
      if (array[i] == search) {
        __CrownBranch(126, 50, 1, __LINE__, __FILE__);
        __CrownLoad(128, (unsigned long )0, 5, (long long )0, (double )0, (char *)"",
                    0, (char)0, (char)0);
        __CrownStore(129, (unsigned long )(& __retres5));
#line 65
        __retres5 = 0;
#line 65
        goto return_label;
      } 
        #line 65
        else {
        __CrownBranch(127, 52, 0, __LINE__, __FILE__);

      }
      }
      __CrownLoad(132, (unsigned long )(& i), 5, (long long )i, (double )i, (char *)"",
                  0, (char)0, (char)0);
      __CrownLoad(131, (unsigned long )0, 5, (long long )1, (double )1, (char *)"",
                  0, (char)0, (char)0);
      __CrownApply2(130, 0, 5, (long long )(i + 1), (double )(i + 1));
      __CrownStore(133, (unsigned long )(& i));
#line 64
      i ++;
    }
    while_break: /* CIL Label */ ;
    }
    __CrownLoad(134, (unsigned long )0, 5, (long long )1, (double )1, (char *)"",
                0, (char)0, (char)0);
    __CrownStore(135, (unsigned long )(& __retres5));
#line 68
    __retres5 = 1;
#line 68
    goto return_label;
  } 
    #line 63
    else {
    __CrownBranch(115, 57, 0, __LINE__, __FILE__);
    __CrownLoad(138, (unsigned long )(& array[idx]), 5, (long long )array[idx], (double )array[idx],
                (char *)"", 0, (char)0, (char)0);
    __CrownLoad(137, (unsigned long )(& search), 5, (long long )search, (double )search,
                (char *)"", 0, (char)0, (char)0);
    __CrownApply2(136, 13, 5, (long long )(array[idx] == search), (double )(array[idx] == search));
    __CrownStore(139, (unsigned long )(& __retres5));
#line 70
    __retres5 = array[idx] == search;
#line 70
    goto return_label;
  }
  }
  return_label: /* CIL Label */ 
  {
  __CrownLoad(140, (unsigned long )(& __retres5), 5, (long long )__retres5, (double )__retres5,
              (char *)"", 0, (char)0, (char)0);
  __CrownReturn(141);
#line 61
  return (__retres5);
  }
}
}
#line 73 "bin-search-crown.c"
int check2(void) 
{ 
  int i ;
  int __retres2 ;

  {
  __CrownCall(142, 4);

  __CrownLoad(143, (unsigned long )0, 5, (long long )0, (double )0, (char *)"", 0,
              (char)0, (char)0);
  __CrownStore(144, (unsigned long )(& i));
#line 74
  i = 0;
  {
#line 74
  while (1) {
    while_continue: /* CIL Label */ ;
    {
    __CrownLoad(147, (unsigned long )(& i), 5, (long long )i, (double )i, (char *)"",
                0, (char)0, (char)0);
    __CrownLoad(146, (unsigned long )(& n), 5, (long long )n, (double )n, (char *)"",
                0, (char)0, (char)0);
    __CrownApply2(145, 20, 5, (long long )(i < n), (double )(i < n));
#line 74
    if (i < n) {
      __CrownBranch(148, 65, 1, __LINE__, __FILE__);

    } 
      #line 74
      else {
      __CrownBranch(149, 66, 0, __LINE__, __FILE__);
#line 74
      goto while_break;
    }
    }
    {
    __CrownLoad(152, (unsigned long )(& old_array[i]), 5, (long long )old_array[i],
                (double )old_array[i], (char *)"", 0, (char)0, (char)0);
    __CrownLoad(151, (unsigned long )(& array[i]), 5, (long long )array[i], (double )array[i],
                (char *)"", 0, (char)0, (char)0);
    __CrownApply2(150, 14, 5, (long long )(old_array[i] != array[i]), (double )(old_array[i] != array[i]));
#line 75
    if (old_array[i] != array[i]) {
      __CrownBranch(153, 68, 1, __LINE__, __FILE__);
      __CrownLoad(155, (unsigned long )0, 5, (long long )0, (double )0, (char *)"",
                  0, (char)0, (char)0);
      __CrownStore(156, (unsigned long )(& __retres2));
#line 75
      __retres2 = 0;
#line 75
      goto return_label;
    } 
      #line 75
      else {
      __CrownBranch(154, 70, 0, __LINE__, __FILE__);

    }
    }
    __CrownLoad(159, (unsigned long )(& i), 5, (long long )i, (double )i, (char *)"",
                0, (char)0, (char)0);
    __CrownLoad(158, (unsigned long )0, 5, (long long )1, (double )1, (char *)"",
                0, (char)0, (char)0);
    __CrownApply2(157, 0, 5, (long long )(i + 1), (double )(i + 1));
    __CrownStore(160, (unsigned long )(& i));
#line 74
    i ++;
  }
  while_break: /* CIL Label */ ;
  }
  __CrownLoad(161, (unsigned long )0, 5, (long long )1, (double )1, (char *)"", 0,
              (char)0, (char)0);
  __CrownStore(162, (unsigned long )(& __retres2));
#line 77
  __retres2 = 1;
  return_label: /* CIL Label */ 
  {
  __CrownLoad(163, (unsigned long )(& __retres2), 5, (long long )__retres2, (double )__retres2,
              (char *)"", 0, (char)0, (char)0);
  __CrownReturn(164);
#line 73
  return (__retres2);
  }
}
}
#line 88
int main(void) ;
#line 88 "bin-search-crown.c"
static int cnt_symbolic_var___1  =    1;
#line 79 "bin-search-crown.c"
int main(void) 
{ 
  int search ;
  int idx ;
  int i ;
  int tmp ;
  int tmp___0 ;
  int __retres6 ;

  {
  __globinit_bin_search_crown();
  __CrownCall(166, 5);
  __CrownClearStack(165);
#line 82
  setup_array();
  __CrownClearStack(167);
  __CrownLoad(168, (unsigned long )0, 5, (long long )0, (double )0, (char *)"", 0,
              (char)0, (char)0);
  __CrownStore(169, (unsigned long )(& i));
#line 83
  i = 0;
#line 83
  while (1) {
    while_continue: /* CIL Label */ ;
    {
    __CrownLoad(172, (unsigned long )(& i), 5, (long long )i, (double )i, (char *)"",
                0, (char)0, (char)0);
    __CrownLoad(171, (unsigned long )(& n), 5, (long long )n, (double )n, (char *)"",
                0, (char)0, (char)0);
    __CrownApply2(170, 20, 5, (long long )(i < n), (double )(i < n));
#line 83
    if (i < n) {
      __CrownBranch(173, 80, 1, __LINE__, __FILE__);

    } 
      #line 83
      else {
      __CrownBranch(174, 81, 0, __LINE__, __FILE__);
#line 83
      goto while_break;
    }
    }
    __CrownLoad(175, (unsigned long )(& array[i]), 5, (long long )array[i], (double )array[i],
                (char *)"", 0, (char)0, (char)0);
    __CrownStore(176, (unsigned long )(& old_array[i]));
#line 83
    old_array[i] = array[i];
    __CrownLoad(179, (unsigned long )(& i), 5, (long long )i, (double )i, (char *)"",
                0, (char)0, (char)0);
    __CrownLoad(178, (unsigned long )0, 5, (long long )1, (double )1, (char *)"",
                0, (char)0, (char)0);
    __CrownApply2(177, 0, 5, (long long )(i + 1), (double )(i + 1));
    __CrownStore(180, (unsigned long )(& i));
#line 83
    i ++;
  }
  while_break: /* CIL Label */ 
#line 88
  __CrownInt(& search, cnt_symbolic_var___1, 88, (char *)"bin-search-crown.c", "search");
  __CrownLoad(183, (unsigned long )(& cnt_symbolic_var___1), 5, (long long )cnt_symbolic_var___1,
              (double )cnt_symbolic_var___1, (char *)"", 0, (char)0, (char)0);
  __CrownLoad(182, (unsigned long )0, 5, (long long )1, (double )1, (char *)"", 0,
              (char)0, (char)0);
  __CrownApply2(181, 0, 5, (long long )(cnt_symbolic_var___1 + 1), (double )(cnt_symbolic_var___1 + 1));
  __CrownStore(184, (unsigned long )(& cnt_symbolic_var___1));
#line 88
  cnt_symbolic_var___1 ++;
  __CrownLoad(185, (unsigned long )(& search), 5, (long long )search, (double )search,
              (char *)"", 0, (char)0, (char)0);
#line 90
  idx = bin_search(search);
  __CrownHandleReturn(187, 5, (long long )idx, (double )idx);
  __CrownStore(186, (unsigned long )(& idx));
  __CrownLoad(188, (unsigned long )(& idx), 5, (long long )idx, (double )idx, (char *)"",
              0, (char)0, (char)0);
  __CrownLoad(189, (unsigned long )(& search), 5, (long long )search, (double )search,
              (char *)"", 0, (char)0, (char)0);
#line 94
  tmp = check(idx, search);
  __CrownHandleReturn(191, 5, (long long )tmp, (double )tmp);
  __CrownStore(190, (unsigned long )(& tmp));
  __CrownLoad(192, (unsigned long )(& tmp), 5, (long long )tmp, (double )tmp, (char *)"",
              0, (char)0, (char)0);
#line 94
  if (tmp) {
    __CrownBranch(193, 86, 1, __LINE__, __FILE__);

  } 
    #line 94
    else {
    __CrownBranch(194, 87, 0, __LINE__, __FILE__);
    __CrownLoad(195, (unsigned long )0, 6, (long long )"check(idx,search)", 8, (char *)"",
                0, (char)0, (char)0);
    __CrownLoad(196, (unsigned long )0, 6, (long long )"bin-search-crown.c", 8, (char *)"",
                0, (char)0, (char)0);
    __CrownLoad(197, (unsigned long )0, 4, (long long )94U, (double )94U, (char *)"",
                0, (char)0, (char)0);
    __CrownLoad(198, (unsigned long )0, 6, (long long )"main", 8, (char *)"", 0, (char)0,
                (char)0);
#line 94
    __assert_fail("check(idx,search)", "bin-search-crown.c", 94U, "main");
    __CrownClearStack(199);
  }
#line 95
  tmp___0 = check2();
  __CrownHandleReturn(201, 5, (long long )tmp___0, (double )tmp___0);
  __CrownStore(200, (unsigned long )(& tmp___0));
  __CrownLoad(202, (unsigned long )(& tmp___0), 5, (long long )tmp___0, (double )tmp___0,
              (char *)"", 0, (char)0, (char)0);
#line 95
  if (tmp___0) {
    __CrownBranch(203, 90, 1, __LINE__, __FILE__);

  } 
    #line 95
    else {
    __CrownBranch(204, 91, 0, __LINE__, __FILE__);
    __CrownLoad(205, (unsigned long )0, 6, (long long )"check2()", 8, (char *)"",
                0, (char)0, (char)0);
    __CrownLoad(206, (unsigned long )0, 6, (long long )"bin-search-crown.c", 8, (char *)"",
                0, (char)0, (char)0);
    __CrownLoad(207, (unsigned long )0, 4, (long long )95U, (double )95U, (char *)"",
                0, (char)0, (char)0);
    __CrownLoad(208, (unsigned long )0, 6, (long long )"main", 8, (char *)"", 0, (char)0,
                (char)0);
#line 95
    __assert_fail("check2()", "bin-search-crown.c", 95U, "main");
    __CrownClearStack(209);
  }
  __CrownLoad(210, (unsigned long )0, 5, (long long )0, (double )0, (char *)"", 0,
              (char)0, (char)0);
  __CrownStore(211, (unsigned long )(& __retres6));
#line 97
  __retres6 = 0;
  __CrownLoad(212, (unsigned long )(& __retres6), 5, (long long )__retres6, (double )__retres6,
              (char *)"", 0, (char)0, (char)0);
  __CrownReturn(213);
#line 79
  return (__retres6);
}
}
void __globinit_bin_search_crown(void) 
{ 


  {
  __CrownInit(214);
}
}
