/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is true */

#line 5 "limit3-array.c"
void __globinit_limit3_array(void) ;
extern void __CrownInit(int id )  __attribute__((__crown_skip__)) ;
extern void __CrownCheckSymbolic(int id , char *fname )  __attribute__((__crown_skip__)) ;
extern void __CrownEnableSymbolic(int id , char *fname )  __attribute__((__crown_skip__)) ;
extern void __CrownSetCallerCalleeName(int id , char *fname , char *fname2 )  __attribute__((__crown_skip__)) ;
extern void __CrownHandleReturn(int id , int type , long long val , double fp_val )  __attribute__((__crown_skip__)) ;
extern void __CrownReturn(int id )  __attribute__((__crown_skip__)) ;
extern void __CrownCall(int id , unsigned int fid )  __attribute__((__crown_skip__)) ;
extern void __CrownBranch(int id , int bid , unsigned char b , int line , char *fname )  __attribute__((__crown_skip__)) ;
extern void __CrownApply2(int id , int op , int type , long long val , double fp_val )  __attribute__((__crown_skip__)) ;
extern void __CrownApply1(int id , int op , int type , long long val , double fp_val )  __attribute__((__crown_skip__)) ;
extern void __CrownClearStack(int id )  __attribute__((__crown_skip__)) ;
extern void __CrownStore(int id , unsigned long addr )  __attribute__((__crown_skip__)) ;
extern void __CrownLoad(int id , unsigned long addr , int type , long long val , double fp_val )  __attribute__((__crown_skip__)) ;
#line 362 "/usr/include/stdio.h"
extern int printf(char const   * __restrict  __format  , ...) ;
#line 376 "/mnt/d/ubuntu/CROWN-sym_assume/bin/../include/crown.h"
extern void __CrownInt(int *x , int cnt_sym_var , int ln , char *fname  , ...)  __attribute__((__crown_skip__)) ;
#line 11 "limit3-array.c"
int main(void) ;
#line 11 "limit3-array.c"
static int cnt_symbolic_var  =    1;
#line 5 "limit3-array.c"
int main(void) 
{ 
  int i ;
  int array[4] ;
  int __retres3 ;

  {
  __globinit_limit3_array();
  __CrownCheckSymbolic(3, "main");
  __CrownCall(2, 1);
  __CrownClearStack(1);
  __CrownLoad(4, (unsigned long )0, 5, (long long )0, (double )0);
  __CrownStore(5, (unsigned long )(& i));
#line 10
  i = 0;
#line 10
  while (1) {
    while_continue: /* CIL Label */ ;
    {
    __CrownLoad(8, (unsigned long )(& i), 5, (long long )i, (double )i);
    __CrownLoad(7, (unsigned long )0, 5, (long long )4, (double )4);
    __CrownApply2(6, 20, 5, (long long )(i < 4), (double )(i < 4));
#line 10
    if (i < 4) {
      __CrownBranch(9, 6, 1, __LINE__, __FILE__);

    } 
      #line 10
      else {
      __CrownBranch(10, 7, 0, __LINE__, __FILE__);
#line 10
      goto while_break;
    }
    }
#line 11
    __CrownInt(& array[i], cnt_symbolic_var, 11, (char *)"limit3-array.c", "array[i]");
    __CrownLoad(13, (unsigned long )(& cnt_symbolic_var), 5, (long long )cnt_symbolic_var,
                (double )cnt_symbolic_var);
    __CrownLoad(12, (unsigned long )0, 5, (long long )1, (double )1);
    __CrownApply2(11, 0, 5, (long long )(cnt_symbolic_var + 1), (double )(cnt_symbolic_var + 1));
    __CrownStore(14, (unsigned long )(& cnt_symbolic_var));
#line 11
    cnt_symbolic_var ++;
    __CrownLoad(17, (unsigned long )(& i), 5, (long long )i, (double )i);
    __CrownLoad(16, (unsigned long )0, 5, (long long )1, (double )1);
    __CrownApply2(15, 0, 5, (long long )(i + 1), (double )(i + 1));
    __CrownStore(18, (unsigned long )(& i));
#line 10
    i ++;
  }
  while_break: /* CIL Label */ 
  __CrownLoad(21, (unsigned long )(& array[1]), 5, (long long )array[1], (double )array[1]);
  __CrownLoad(20, (unsigned long )0, 5, (long long )3, (double )3);
  __CrownApply2(19, 13, 5, (long long )(array[1] == 3), (double )(array[1] == 3));
#line 13
  if (array[1] == 3) {
    __CrownBranch(22, 11, 1, __LINE__, __FILE__);
    __CrownLoad(24, (unsigned long )0, 6, (long long )((char const   * __restrict  )"array[1] is 3\n"),
                8);
    __CrownSetCallerCalleeName(25, "main", "printf");
#line 14
    printf((char const   * __restrict  )"array[1] is 3\n");
    __CrownEnableSymbolic(27, "main");
    __CrownClearStack(26);
  } 
    #line 13
    else {
    __CrownBranch(23, 12, 0, __LINE__, __FILE__);
    __CrownLoad(28, (unsigned long )0, 6, (long long )((char const   * __restrict  )"array[1] is not 3 but %d\n"),
                8);
    __CrownLoad(29, (unsigned long )(& array[1]), 5, (long long )array[1], (double )array[1]);
    __CrownSetCallerCalleeName(30, "main", "printf");
#line 15
    printf((char const   * __restrict  )"array[1] is not 3 but %d\n", array[1]);
    __CrownEnableSymbolic(32, "main");
    __CrownClearStack(31);
  }
  __CrownLoad(33, (unsigned long )0, 5, (long long )0, (double )0);
  __CrownStore(34, (unsigned long )(& __retres3));
#line 16
  __retres3 = 0;
  __CrownLoad(35, (unsigned long )(& __retres3), 5, (long long )__retres3, (double )__retres3);
  __CrownReturn(36);
#line 5
  return (__retres3);
}
}
void __globinit_limit3_array(void) 
{ 


  {
  __CrownInit(37);
}
}
